# Use the latest version of Ubuntu as the base image
FROM ubuntu:latest

# Update APT and upgrade any installed packages
RUN apt-get update && apt-get upgrade -y

# Echo "Hello, World!"
CMD echo "Hello, World!"
