version: '3.8'

services:
  front-end:
    build:
      context: .
      dockerfile: Dockerfile.front-end
    ports:
      - "8080:80"
    depends_on:
      - back-end

  back-end:
    build:
      context: .
      dockerfile: Dockerfile.back-end
    ports:
      - "5000:5000"
